### ISSUE TITLE
Support python3

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontdiffenator#11]
This tool only supports python 2.7 atm. Given the recent push on FB, I'd like to do this sooner rather than later.

The big question, should we completely drop 2.7 support? are the necessary hacks needed in order to support both 2 & 3 worth it?

**Comment by davelab6** [comment]
Yes, completely drop v2

**Comment by davelab6** [comment]
Done in https://github.com/googlefonts/fontdiffenator/commit/41972efecc06866fb8dc36bf20b34a713772b9dd
