### ISSUE TITLE
Don't parse ttx output

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/fontdiffenator#2]
Don't make XML and parse it. Delete https://github.com/googlefonts/fontdiffenator/blob/diff_cleanup/Lib/diffenator/ttxfont.py.

AFAIK the main options here are:

- wait for otLib (IIRC it's not ready yet?)
- write your own code similar to https://android.googlesource.com/platform/frameworks/base/+/master/tools/fonts/fontchain_linter.py#132

**Comment by davelab6** [comment]
@m4rc1e said offline,

> This approach cannot parse all lookup types. [HBInput Generator](https://github.com/googlei18n/nototools/blob/master/nototools/hb_input.py) is much closer. I've been using it to generate generate glyph palettes. the only downside is it cannot use the local feature properly, since it completely skips languages.

**Comment by m4rc1e** [comment]
ttx parsing was dropped in #3. Current implementation uses Nototool's HbInput, https://github.com/googlei18n/nototools/blob/master/nototools/hb_input.py to access unencoded glyphs.

Still not 100% happy with this solution, too slow on complex fonts and doesn't take languages into consideration. However, it's better than what we had before.
