### ISSUE TITLE
Improve/finalise api for v1.0.0

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontdiffenator#28]
Before rolling out the v1.0.0 release, I'd like to get the api finalised.

It currently has a C style api.

```
# We have to pass the diff to each function
diff = diff_fonts(font_a, font_b)
report = diff_report(diff, font_a, font_b)
gifs = diff_renders(diff, font_a, font_b, dst='/path/out')
```

It may better if we move to an OOP solution. 

```
# DiffFonts is a container (similar to a Pandas DataFrame).
diff = DiffFonts(font_a, font_b)
report = diff.to_txt('/path/out.txt')
report_md = diff.to_md('/path/out.md')
gifs = diff.to_gifs('/path/out_dir')
```

**Comment by m4rc1e** [comment]
Done in #35

**Comment by davelab6** [comment]
Winner

**Comment by chrissimpkins** [comment]
It looks like the C style approach is still documented on the README. 

https://github.com/googlefonts/fontdiffenator#python-google-fonts

Look forward to taking this for a spin Marc.  Looks fantastic!
