### ISSUE TITLE
Surface area check should 'remove overlap' before checking

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontdiffenator#4]
Currently diffenator has a simple heuristic for surface area checks, that has this result:

```
**glyphs 1 modified**
glyph               diff
Ecircumflex         131787.083333
```

<img width="370" alt="screen shot 2018-05-03 at 09 43 24" src="https://user-images.githubusercontent.com/261579/39580142-7358fd9c-4eb6-11e8-9132-15bbecab96e2.png">

This should not result in a difference, by "simply" running a (time intensive) remove overlap operation over glyphs before comparing them. 

However, since the addition/removal of overlaps can be an oversight, both the current and future comparisons should be run, and if their results are different, then the 'diff' result should be annotated like that. Eg

```
**glyphs 1 modified**
glyph               diff            diff.removeOverlap
Ecircumflex         131787.083333   0
```

**Comment by rsheeter** [comment]
Why not render the damn thing and compare the rendering? - surface area can be identical but modified in different ways (pull two different points, translate the whole block in different directions, etc) to yield the wrong result.

**Comment by anthrotype** [comment]
> Why not render the damn thing and compare the rendering?

that's what notodiff does
https://github.com/googlei18n/nototools/blob/1498e738409a8fde3a157d00ad320ffb3500d498/nototools/shape_diff.py#L106

**Comment by m4rc1e** [comment]
@rsheeter @anthrotype It's pretty slow and it relies on Harfbuzz.

A requirement was to make this as dependency free as possible. I do see your point and am happy to have such an approach enabled by default.

**Comment by chrissimpkins** [comment]
I spoke with Behdad a few months ago about using the StatisticsPen in fontTools to compare glyph center of mass to achieve a binary "does the shape differ?" across builds answer (and not where the shape differs).  The glyph center of mass should be pretty sensitive to changes in contours but it sounded like there were limitations when overlaps are present in the current implementation of the pen.  

Here is Behdad's comment in the module:

> if the glyph shape is self-intersecting, the values are not correct
(but well-defined). As such, area will be negative if contour
directions are clockwise.  Moreover, variance might be negative
if the shapes are self-intersecting in certain ways.

Another possible approach to this problem, but not one that gets around the removal of overlaps issue.  Perhaps the value of that calculation is not important if it changes reliably in the presence of overlaps when the contour changes?  That is math beyond my comprehension :)

That pen supports area calculations as well though with similar overlap constraints.

**Comment by davelab6** [comment]
Why not just run a removeOverlap() before running the StatisticPen over the
glyph?

**Comment by chrissimpkins** [comment]
> Why not just run a removeOverlap() before running the StatisticPen over the glyph?

My understanding is that this would address the problem.  I was trying to address your concerns about overlap removal being a time intensive process across all glyphs in a set.   Perhaps @behdad could weigh in?  Unless you need the calculated values (which IMO you probably don't for a diff), you may be able to skip that step and simply calculate a delta across build 1 v/ build 2.  If it differs, then there is a change.  If it doesn't, then there is not.

**Comment by chrissimpkins** [comment]
For one off checks absolutely.  If you are batching the entire GF collection in the setting of modifications in build tooling or for some other broad scale need then it probably matters a great deal.

**Comment by chrissimpkins** [comment]
But I am getting way ahead of my understanding here.  I don't want to mislead you about the COM measure.  Would be appropriate for Behdad or someone else versed in this to weigh in.   Just an idea.

**Comment by m4rc1e** [comment]
I care about speed. This tool/lib will be used in the web app http://www.gf-regression.com. However, I’m open to having an option to compare rendered diffs.

**Comment by chrissimpkins** [comment]
> However, I’m open to having an option to compare rendered diffs

@m4rc1e Another idea.  If you are using an approach that renders to images, you might have a look at some of the image similarity software out there to achieve this.  They are designed for information loss testing and a change in the rendered glyph should register as information change in these calculations (maybe? the RBGA considerations vs. greyscale data in glyphs may require a different approach than those that I am aware of).

The [SSIM measure](https://ece.uwaterloo.ca/~z70wang/research/ssim) is one that I know about and there is free, open source software available to compare pre/post images:

https://pngquant.org/dssim.html (also see https://kornel.ski/dssim)

Compiled and fast executable + available as a library.  Project is maintained by the pngquant author Kornel Lesinski.  It would be very interesting to experiment and see if there are ways to define visually relevant changes at reading sizes in bodies of rendered text rather than in isolated glyph renders.  Maybe way off the path for what your plans / needs are here, but an interesting, relevant question and possibly amenable to testing.

**Comment by m4rc1e** [comment]
@chrissimpkins thank you for reply. We already have a way to do this.

We control the web app using [diffbrowsers](https://github.com/googlefonts/diffbrowsers). This tool allows us to take screenshots using browserstack.


Results can be seen in prs sent to google/fonts

https://github.com/google/fonts/pull/1475
https://github.com/google/fonts/pull/1452
