### ISSUE TITLE
Why might some diffs not be running? 

### ISSUE THREAD

**Issue by thundernixon** [googlefonts/fontdiffenator#42]
I'm making some diff checks of the latest versions of IBM Plex versus the versions currently in the google/fonts repo. I'm doing this work at https://github.com/thundernixon/plex/tree/diff-QA/gfonts-qa.

However, even though there are new and old versions of both `Sans Condensed` and `Mono` versions of Plex, these checks don't generate gifs (even though my tests run on `Sans` and `Serif` families do generate gifs). 

What are some of thes things that might cause this? The fonts filenames match. I assume maybe the name tables may not match closely enough for diffenator to both making tests? Or, have I missed something else?

### Sans Condensed
Couldn't test... even when working directly in the command line:

```
$ diffenator gfonts-qa/currently-hosted-fonts/ibmplexsanscondensed/IBMPlexSansCondensed-Bold.ttf IBM-Plex-Sans-Condensed/fonts/complete/ttf/IBMPlexSansCondensed-Bold.ttf -r gfonts-qa/currently-hosted-fonts/ibmplexsanscondensed/IBMPlexSansCondensed-Bold-diffs  -ol 200
-------------------------------------------------------------
INFO:diffenator.diff:'diff_nametable'  0.09 ms
INFO:diffenator.diff:'diff_attribs'  0.15 ms
INFO:diffenator.diff:'diff_glyphs'  1.77 ms
INFO:diffenator.diff:'diff_kerning'  212.96 ms
INFO:diffenator.diff:'diff_metrics'  1.26 ms
INFO:diffenator.diff:'diff_marks'  15.11 ms
INFO:diffenator.diff:'diff_marks'  0.54 ms
**Diffenator**
```

It did create the requested folder for output gifs, but this folder was empty.

### Mono
Similar to Sans Condensed, diffenator didn't really check Mono styles.

```
$ diff-fonts gfonts-qa/currently-hosted-fonts/ibmplexmono IBM-Plex-Mono/fonts/complete/ttf
-------------------------------------------------------------
diffing IBMPlexMono-Bold.ttf
WARNING:diffenator.dump:Font doesn't have a GPOS kern feature
WARNING:diffenator.dump:Font doesn't have a GPOS kern feature
INFO:diffenator.diff:'diff_nametable'  0.10 ms
INFO:diffenator.diff:'diff_attribs'  0.15 ms
INFO:diffenator.diff:'diff_glyphs'  2.95 ms
INFO:diffenator.diff:'diff_kerning'  0.68 ms
INFO:diffenator.diff:'diff_metrics'  1.42 ms
INFO:diffenator.diff:'diff_marks'  19.13 ms
INFO:diffenator.diff:'diff_marks'  0.54 ms
**Diffenator**
```

**Comment by m4rc1e** [comment]
Fonts are identical. I'll make this clearer.
