### ISSUE TITLE
Diff VFs and correctly compare glyphs available

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontdiffenator#5]
When glyphs become accessible or not from OT lang features, they get reported as missing/added. 

@m4rc1e says offline he can inspect the implementation of varLib mutator to prove this.

**Comment by m4rc1e** [comment]
The first sentence is true. We can determine whether or not a glyph is accessible. 

The 2nd, I need to do some research first.

**Comment by m4rc1e** [comment]
Closing. Fixed in #15
