### ISSUE TITLE
Optional param to only diff mark combos which shaping engines allow

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontdiffenator#7]
Since each font builder has their own way of building GPOS mark features, I'm tempted to only diff combos which shaping engines allow.

**Comment by anthrotype** [comment]
what are these "combos which shaping engines allow"?

**Comment by m4rc1e** [comment]
@anthrotype I assumed that shaping engines could only add Nonspacing marks to certain base glyphs... I'm wrong.

![screen shot 2018-06-19 at 13 16 47](https://user-images.githubusercontent.com/7525512/41596691-0df374a0-73c3-11e8-89e5-50453f8b7be2.png)

**Comment by m4rc1e** [comment]
Interestingly in Mac OS X, it will position glyphs which are not Nonspacing Marks as well.

![screen shot 2018-06-19 at 14 01 00](https://user-images.githubusercontent.com/7525512/41599355-cb043028-73ca-11e8-8c76-08d8976c76c9.png)

![screen shot 2018-06-19 at 14 13 11](https://user-images.githubusercontent.com/7525512/41599393-ebf86a38-73ca-11e8-8a7d-6e5e885fb1ef.png)
*D positioned with acute (U+00B4)*

**Comment by anthrotype** [comment]
check that font's GDEF table, and see if the "acute" glyph is marked as class 3 (combining mark)

**Comment by anthrotype** [comment]
Ok it’s not marked as such, but still it is included in the Coverage table of the mark class for all the top marks, along with acutcomb etc so for the sake of the mark feature it is a combining mark

**Comment by anthrotype** [comment]
The GDEF category applies for things like IgnoreMarks lookup flags
